### PR TITLE
resolve build error caused by const_iterator

### PR DESCRIPTION
**Pull request by BrandonHe**
### Target:
This PR is try to fix issue #7 
### Change log:
change ```const_iterator``` to ```iterator``` in API ```void AppList::appUnregistered```

### CODE REVIEW

**Comment by BrandonHe** [comment]
@smartdevice475 @bahamut65536 
Please review, thanks

**Review by luwanjia — COMMENTED** [review]
Reviewed

**Review by ilikegithubcom — COMMENTED** [review]
Reviewed, No problem.

**Review by bahamut65536 — COMMENTED** [review]
reviewed

**Comment by fanqiang001** [comment]
reviewed

**Pull request merged**
